plugins { id 'net.fabricmc.fabric-loom' version '1.17.20' }

version = '1.0.0+26.3'
group = 'com.thenathe'
base { archivesName = 'toolpouch-polymer-compat' }
repositories { maven { url = 'https://maven.nucleoid.xyz/' } }
dependencies {
    minecraft 'com.mojang:minecraft:26.3'
    implementation 'net.fabricmc:fabric-loader:0.19.5'
    implementation 'net.fabricmc.fabric-api:fabric-api:0.161.0+26.3'
    implementation 'eu.pb4:polymer-core:0.18.2+26.3'
    implementation 'eu.pb4:polymer-resource-pack:0.18.2+26.3'
    compileOnly files('libs/toolpouch-fabric-1.1.10+26.3.jar', 'libs/mapstitch-polymer-compat-1.0.1+26.3.jar')
}
processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand(version: project.version) }
}
tasks.withType(JavaCompile).configureEach {
    if (providers.gradleProperty('compilerVersion').isPresent()) {
        javaCompiler = javaToolchains.compilerFor {
            languageVersion = JavaLanguageVersion.of(providers.gradleProperty('compilerVersion').get())
        }
    }
    options.encoding = 'UTF-8'
    options.release = 25
}
java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}
jar { from('LICENSE') }
if (file('qa.gradle').exists()) apply from: 'qa.gradle'
